# Generated by Django 3.1 on 2020-08-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200831_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='UploadImage',
        ),
        migrations.RenameField(
            model_name='uploadimage',
            old_name='hotel_Main_Img',
            new_name='Img',
        ),
    ]
