# Generated by Django 3.1 on 2020-09-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200915_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='Img',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='name',
        ),
    ]
