# Generated by Django 3.1 on 2020-09-21 13:54

from django.db import migrations, models
import g3garments.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200915_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHoodiesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=g3garments.storage_backends.PublicMediaStorage(), upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadJeansImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=g3garments.storage_backends.PublicMediaStorage(), upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadShirtsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=g3garments.storage_backends.PublicMediaStorage(), upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadTracksImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=g3garments.storage_backends.PublicMediaStorage(), upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
